name: Android CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create keystore
      run: ./script/create_keystore.sh

    - name: Create local.properties
      run: ./script/create_local_properties.sh

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Detekt
      run: ./gradlew detekt

    - name: Build with Gradle
      run: ./gradlew build

    - name: Log success message
      run: echo "Build finished successfully"
