name: build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create keystore
      run: ./script/create_keystore.sh

    - name: Create local.properties
      run: ./script/create_local_properties.sh

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: oracle
        java-version: 21

    - name: Detekt
      run: ./gradlew detekt

    - name: Build with Gradle
      run: ./gradlew build

    - name: unit tests
      run: ./gradlew testStageDebugUnitTest

    - name: Upload artifact on ui tests failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: Unit test report
        path: '**/app/build/reports/tests/**'

    - name: Build Android test APK
      run: ./gradlew assembleStageDebugAndroidTest

    - name: Upload APKs for UI tests
      uses: actions/upload-artifact@v4
      with:
        name: apks
        path: |
          app/build/outputs/apk/stage/debug/app-stage-debug.apk
          app/build/outputs/apk/androidTest/stage/debug/app-stage-debug-androidTest.apk
        if-no-files-found: error

    - name: Coverage report
      run: ./gradlew jacocoTestCoverageVerification

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: Jacoco report
        path: '**/app/build/jacocoHtml/**'

    - name: Log success message
      run: echo "Build finished successfully"

  ui-tests:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download APKs
      uses: actions/download-artifact@v4
      with:
        name: apks
        path: app/build/outputs/apk

    - name: UI tests
      uses: reactivecircus/android-emulator-runner@v2.33.0
      with:
        api-level: 31
        arch: x86_64
        profile: Nexus 6
        script: |
          adb install -r app/build/outputs/apk/stage/debug/app-stage-debug.apk || exit 1
          adb install -r app/build/outputs/apk/androidTest/stage/debug/app-stage-debug-androidTest.apk || exit 1
          bash -o pipefail -c 'adb shell am instrument -w -r com.marzec.cheatday.debug.test/com.marzec.cheatday.MockTestRunner 2>&1 | tee ui-test.log'

    - name: Upload artifact on UI test failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: UI Tests console log
        path: ui-test.log
